
language: c
compiler:
  - gcc
before_install: 
  - sudo apt-get install libdevice-serialport-perl
  - sudo apt-get install libyaml-perl
  - sudo apt-get install arduino
  - sudo apt-get install arduino-mk
